id: org.kde.kjournaldbrowser
branch: master
runtime: org.kde.Platform
runtime-version: '6.10'
sdk: org.kde.Sdk
command: kjournaldbrowser
rename-icon: "utilities-log-viewer"
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  # X11
  - --share=ipc
  # Windowing
  - --socket=fallback-x11
  - --socket=wayland
  # Hardware Acceleration
  - --device=dri
  # Browse the system journal
  - --filesystem=/var/log/journal:ro
modules:
  - name: kjournald
    buildsystem: cmake-ninja
    config-opts: [ "-DINSTALL_ICONS=ON" ]
    sources:
      - type: dir
        path: .
