id: org.kde.kjournaldbrowser
branch: master
runtime: org.kde.Platform
runtime-version: '6.10'
sdk: org.kde.Sdk
command: kjournaldbrowser
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  # X11
  - --share=ipc
  # Windowing
  - --socket=fallback-x11
  - --socket=wayland
  # Hardware Acceleration
  - --device=dri
  # Browse the system journal
  - --filesystem=/var/log/journal:ro
modules:
  - name: kjournald
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: .
    post-install:
      # Icon is included with breeze in runtime
      - mkdir -p ${FLATPAK_DEST}/share/icons/hicolor/32x32/apps/
      - install -D /usr/share/icons/breeze/apps/32/utilities-log-viewer.svg ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps/${FLATPAK_ID}.svg
      - desktop-file-edit --set-key=Icon --set-value=${FLATPAK_ID} ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
